# Generated by Django 5.0.7 on 2024-07-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Sales Man', 'Sales Man')], default='', max_length=20),
        ),
    ]
